<?php
#echo "Logged in: ".Zend_Debug::dump($this->usuarioLogueado);
?>
<div id="main">
	Role: <?php echo $this->role; ?>
	<h4>Listado de tareas</h4>
	<table border="1">
	    <?php foreach( $this->tasks as $task ) : ?>
	        <tr>
	          <td><?php echo $task->nombre ?></td>
	          <td><?php echo $task->descripcion ?></td>
	        </tr>
	    <?php endforeach; ?>
	</table>
</div>