<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="es" lang="es">

  	<head>
	    <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
	    <title><?php echo $this->escape($this->title); ?></title>
	    <link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl;?>/html/styles/site.css" />
	    <script src="<?php echo $this->baseUrl;?>/html/clientScripts/site.js" type="text/javascript"></script>
	    <script src="<?php echo $this->baseUrl;?>/html/clientScripts/mootools/mootools.js" type="text/javascript"></script>
	  	<script src="<?php echo $this->baseUrl;?>/html/clientScripts/mootools/fvalidator.js" type="text/javascript"></script>
	  	<script src="<?php echo $this->baseUrl;?>/html/clientScripts/mootools/calendar.js" type="text/javascript"></script>
	</head>

	<body>
		<div id="header">
			<img src="<?php echo $this->baseUrl;?>/html/images/logo.jpg" border="0" />
		</div>