		<div id="menu">
			<ul>
				<li class="tit">Menú de ejemplo</li>
				<li><a href="<?php echo $this->baseUrl ?>/noticias/">Noticias</a></li>
				<li><a href="<?php echo $this->baseUrl ?>/conceptos/admin">Conceptos</a></li>
				<li><a href="<?php echo $this->baseUrl ?>/tipos_gastos/admin">Tipo de gastos</a></li>
				<li><a href="<?php echo $this->baseUrl ?>/gastos/admin">Gastos</a></li>
				<li><a href="<?php echo $this->baseUrl ?>/usuarios/">Usuarios</a></li>
				<li class="tit"><a href="<?php echo $this->baseUrl ?>/autenticacion/admin/logout">Salir</a></li>
			</ul>
		</div>