<div id="menu">
	<ul>
		<li class="tit">Menú</li>
		<!-- <li><a href="<?php echo $this->baseUrl ?>/frontend/">Front end</a></li> -->
		<?php if($this->usuarioLogueado): ?>
			<li><a href="<?php echo $this->baseUrl ?>/frontend/task">List Tasks</a></li>
			<li><a href="<?php echo $this->baseUrl ?>/frontend/task/add">Add Task</a></li>
			<!-- <li><a href="<?php echo $this->baseUrl ?>/backend/">Back end</a></li> -->
			<li><a href="<?php echo $this->baseUrl ?>/frontend/login/logout">Salir</a></li>
		<?php else: ?>
		<li><a href="<?php echo $this->baseUrl ?>/frontend/login/login">Login</a></li>
		<?php endif; ?>

	</ul>
</div>