<?php
#echo "Logged in: ".Zend_Debug::dump($this->usuarioLogueado);
?>
<div id="main">
	Role: <?php echo $this->role; ?>
	<h4>Listado de tareassss</h4>
	<table>
			<tr class="header">
	          <td>Name</td>
	          <td>Desc.</td>
	          <td>From</td>
	          <td>To</td>
	          <td>Status</td>
	        </tr>
	    <?php foreach( $this->tasks as $task ) : ?>
	        <tr>
	          <td><?php echo $task->tarea_nombre ?></td>
	          <td><?php echo $task->tarea_descripcion ?></td>
	          <td><?php echo $task->departamento_origen ?></td>
	          <td><?php echo $task->departamento_destino ?></td>
	          <td><?php echo $task->tarea_estado ?></td>
	        </tr>
	    <?php endforeach; ?>
	</table>
</div>