<?php
#echo "Logged in: ".Zend_Debug::dump($this->usuarioLogueado);
?>
<div id="main">
	Role: <?php echo $this->role; ?>
	<h4>Listado de tareassss</h4>
	<table>
			<tr class="header">
	          <td>Nombre</td>
	          <td>Desc.</td>
	          <td>Origen</td>
	          <td>Destino</td>
	          <td>Inicio</td>
	          <td>Fin</td>
	          <td>Estado</td>
	        </tr>
	    <?php foreach( $this->tasks as $task ) : ?>
	        <tr>
	          <td><?php echo $task->tarea_nombre ?></td>
	          <td><?php echo $task->tarea_descripcion ?></td>
	          <td><?php echo $task->departamento_origen ?></td>
	          <td><?php echo $task->departamento_destino ?></td>
	          <td><?php echo $task->tarea_inicio ?></td>
	          <td><?php echo $task->tarea_fin ?></td>
	          <td><a href="<?php echo $this->baseUrl; ?>/frontend/task/view/id/<?php echo $task->tarea_id; ?>"><?php echo $task->tarea_estado ?></a></td>
	        </tr>
	    <?php endforeach; ?>
	</table>
</div>